import { panel, statTile, viewHead, simNote } from '../lib/ui.js';
import { areaChart, barChart } from '../lib/charts.js';
import { icons } from '../lib/icons.js';
import { hhmm, ago, dur } from '../lib/format.js';
import { RANGES, CATEGORIES, seriesFor, timeline, activityStats } from '../data/activity.js';
import { browserActivity, browserStats } from '../data/browser.js';

export const meta = { title: 'ACTIVITY' };

let range = '24H';
let active = new Set(CATEGORIES.map((c) => c.key));

export function render() {
  return `
  ${viewHead('SYNTHETIC EVENT TELEMETRY', 'Activity Graph',
    `${activityStats.total.toLocaleString()} simulated events generated by the mock layer.`,
    `<span class="badge sim">SYNTHETIC</span>`)}

  <div class="grid g-4">
    ${statTile('Total events', activityStats.total)}
    ${statTile('Events / hour', activityStats.perHour, { pad: 2 })}
    ${statTile('Peak window', 19, { delta: `${activityStats.peakHour} simulated peak` })}
    ${statTile('Quiet window', 4, { delta: `${activityStats.quietHour} simulated trough` })}
  </div>

  <div style="margin-top:14px">
    ${panel('EVENT TIMELINE', `
      <div class="panel-pad">
        <div class="filters" style="border:none;padding:0 0 14px">
          ${CATEGORIES.map((c) => `<button class="chip ${active.has(c.key) ? 'on' : ''}" data-cat="${c.key}">
            <i style="display:inline-block;width:7px;height:7px;border-radius:2px;background:${c.color};margin-right:6px"></i>${c.label}</button>`).join('')}
        </div>
        <div class="chart-wrap" id="achart">${chart()}</div>
      </div>`, {
      right: RANGES.map((r) => `<button class="chip ${range === r.key ? 'on' : ''}" data-range="${r.key}">${r.key}</button>`).join(' '),
    })}
  </div>

  <div class="grid" style="grid-template-columns:1fr 1fr;margin-top:14px">
    ${panel('CATEGORY DISTRIBUTION', `<div class="panel-pad chart-wrap">
      ${barChart(activityStats.byCategory.map((c) => c.value), activityStats.byCategory.map((c) => c.label.slice(0, 3)))}
    </div>`)}

    ${panel('SIMULATED BROWSING', `
      <div style="max-height:300px;overflow-y:auto" class="scroll">
      ${browserActivity.map((b) => `
        <div class="loc-row">
          <span style="width:15px;color:var(--info)">${icons.globe}</span>
          <div style="flex:1;min-width:0">
            <div style="font-size:12.5px">${b.title}</div>
            <div class="label" style="margin-top:3px">${b.host} · ${b.cat} · ${dur(b.secs)}</div>
          </div>
          <span class="mono" style="font-size:10px;color:var(--faint)">${ago(b.ts)}</span>
        </div>`).join('')}
      </div>`, {
      right: `<span class="label">${browserStats.sessions} SESSIONS · ${browserStats.domains} FICTIONAL DOMAINS</span>`,
    })}
  </div>

  <div style="margin-top:14px">
    ${panel('RECENT EVENT LOG', `<div class="panel-pad" style="padding-top:6px">${timelineRows()}</div>`)}
  </div>

  <div style="margin-top:14px">${simNote('Charts are computed from a seeded generator with a diurnal curve. No usage statistics are collected from any device or browser.')}</div>
  `;
}

function chart() {
  const { labels, series } = seriesFor(range);
  const shown = series.filter((s) => active.has(s.key));
  if (!shown.length) return `<div class="empty"><div class="glyph">⌀</div><div class="mono" style="font-size:11px;letter-spacing:.14em">NO CATEGORIES SELECTED</div></div>`;
  return areaChart(shown, labels, { colors: shown.map((s) => s.color) });
}

function timelineRows() {
  return timeline(22).map((t) => `
    <div class="tl-item">
      <span class="mono" style="font-size:10.5px;color:var(--faint);padding-top:2px">${hhmm(t.ts)}</span>
      <span class="tl-rail"><i style="border-color:${t.color}"></i></span>
      <div>
        <div style="font-size:12.5px">${t.text}</div>
        <div class="label" style="margin-top:3px">${t.label} · ${t.ref} · ${ago(t.ts).toUpperCase()}</div>
      </div>
    </div>`).join('');
}

export function mount(root, ctx) {
  const target = root.querySelector('#achart');
  const redraw = () => { target.innerHTML = chart(); };

  root.querySelectorAll('[data-range]').forEach((b) => {
    b.onclick = () => {
      range = b.dataset.range;
      root.querySelectorAll('[data-range]').forEach((x) => x.classList.toggle('on', x === b));
      redraw();
      ctx.toast(`Range set to ${range} (synthetic)`);
    };
  });

  root.querySelectorAll('[data-cat]').forEach((b) => {
    b.onclick = () => {
      const k = b.dataset.cat;
      if (active.has(k)) active.delete(k); else active.add(k);
      b.classList.toggle('on', active.has(k));
      redraw();
    };
  });
}
