import { panel, statTile, viewHead, avatar, simNote } from '../lib/ui.js';
import { barChart, donut } from '../lib/charts.js';
import { icons } from '../lib/icons.js';
import { hhmm, dayLabel, dur, ago } from '../lib/format.js';
import { calls, callStats, callVolume, callVolumeLabels } from '../data/calls.js';
import { byId } from '../data/contacts.js';

export const meta = { title: 'CALLS' };

let filter = 'all';

export function render() {
  return `
  ${viewHead('SYNTHETIC VOICE ANALYTICS', 'Call Intelligence',
    'Fictional call log generated by the simulation layer.',
    `<span class="badge sim">SYNTHETIC</span>`)}

  <div class="grid g-4">
    ${statTile('Total calls', callStats.total, { pad: 2, delta: `${dur(callStats.totalSeconds)} total duration` })}
    ${statTile('Incoming', callStats.incoming, { pad: 2, delta: 'received (simulated)' })}
    ${statTile('Outgoing', callStats.outgoing, { pad: 2, delta: 'placed (simulated)' })}
    ${statTile('Missed', callStats.missed, { pad: 2, delta: 'no answer (simulated)' })}
  </div>

  <div class="grid" style="grid-template-columns:1.5fr 1fr;margin-top:14px">
    ${panel('SYNTHETIC CALL VOLUME — 24H', `<div class="panel-pad chart-wrap">${barChart(callVolume, callVolumeLabels)}</div>`,
      { right: `<span class="label">2-HOUR BUCKETS</span>` })}

    ${panel('DIRECTION SPLIT', `
      <div style="display:flex;gap:20px;align-items:center;padding:20px;flex-wrap:wrap">
        <div style="flex:none">${donut([
          { label: 'OUT', value: callStats.outgoing, color: '#5b8def' },
          { label: 'IN', value: callStats.incoming, color: '#3fb27f' },
          { label: 'MISSED', value: callStats.missed, color: '#d8323f' },
        ])}</div>
        <div style="flex:1;min-width:120px">
          <div class="kv"><span class="k">Longest</span><span class="v">${dur(callStats.longest.sec)}</span></div>
          <div class="kv"><span class="k">Average</span><span class="v">${dur(Math.round(callStats.totalSeconds / callStats.total))}</span></div>
          <div class="kv"><span class="k">Top contact</span><span class="v">${byId[callStats.longest.contact].name}</span></div>
          <div class="kv"><span class="k">Network</span><span class="v">SIMULATED</span></div>
        </div>
      </div>`)}
  </div>

  <div style="margin-top:14px">
    ${panel('CALL TIMELINE', `<div id="calllist">${rows()}</div>`, {
      right: [['all', 'ALL'], ['in', 'IN'], ['out', 'OUT'], ['missed', 'MISSED']]
        .map(([k, l]) => `<button class="chip ${filter === k ? 'on' : ''}" data-cfilter="${k}">${l}</button>`).join(' '),
    })}
  </div>

  <div style="margin-top:14px">${simNote('NEXUS does not place, receive, record, or intercept calls. This log is invented data rendered from the local mock layer.')}</div>
  `;
}

function rows() {
  const list = calls.filter((c) => filter === 'all' || c.type === filter);
  if (!list.length) return `<div class="empty"><div class="glyph">⌀</div><div class="mono" style="font-size:11px;letter-spacing:.14em">NO CALLS IN THIS FILTER</div></div>`;
  let lastDay = '';
  return list.map((c) => {
    const p = byId[c.contact];
    const day = dayLabel(c.ts);
    let sep = '';
    if (day !== lastDay) { lastDay = day; sep = `<div style="padding:10px 18px 6px"><span class="label">${day}</span></div>`; }
    const cls = c.type === 'in' ? 'in' : c.type === 'out' ? 'out' : 'missed';
    const ic = c.type === 'in' ? icons.arrowIn : c.type === 'out' ? icons.arrowOut : icons.missed;
    return `${sep}<div class="call-row">
      <span class="call-icon ${cls}">${ic}</span>
      <div style="display:flex;align-items:center;gap:11px;min-width:0">
        ${avatar(p.name, { size: 'xs', hue: p.hue })}
        <div style="min-width:0">
          <div style="font-size:13px;font-weight:520">${p.full}</div>
          <div class="label" style="margin-top:2px">${p.number}</div>
        </div>
      </div>
      <div class="mono" style="font-size:10.5px;color:var(--muted)">${c.type.toUpperCase()} · ${c.net}</div>
      <div class="mono" style="font-size:11.5px">${c.sec ? dur(c.sec) : '—'}</div>
      <div class="mono" style="font-size:11px;color:var(--muted);text-align:right">${hhmm(c.ts)}<div class="label" style="margin-top:2px">${ago(c.ts)}</div></div>
    </div>`;
  }).join('');
}

export function mount(root, ctx) {
  root.querySelectorAll('[data-cfilter]').forEach((b) => {
    b.onclick = () => {
      filter = b.dataset.cfilter;
      root.querySelectorAll('[data-cfilter]').forEach((x) => x.classList.toggle('on', x === b));
      root.querySelector('#calllist').innerHTML = rows();
    };
  });
  ctx.toast('Synthetic call log rendered');
}
